# Window, WindowText, Base, AlternateBase, ToolTipBase, ToolTipText,
# Text, Button, ButtonText, BrightText, Light, Midlight, Dark, Mid,
# Shadow, Highlight, HighlightedText, Link, LinkVisited, PlaceholderText,
# Inactive_Window, Inactive_WindowText

[ColorScheme]
active_colors={background}ff, {foreground}ff, {background}3f, {color0}5f, {color0}8f, {color1}ff, {color4}ff, {color0}af, {color2}ff, {color3}ff, {color15}ff, {color14}ff, {background}ff, {color0}cf, {color0}ff, {color0}ff, {foreground}ff, {color6}ff, {color7}ff, {color8}ff, {color0}ff, {foreground}ff
disabled_colors={color3}ff, {color1}ff, {color1}ff, {color7}ff, {color1}ff, {color1}ff, {color3}ff, {color5}ff, {color1}ff, {color1}ff, {color1}ff, {color1}ff, {color3}ff, {color3}ff, {color3}ff, {color1}ff, {color5}ff, {color1}ff, {color3}ff, {color1}ff, {color3}ff, {color2}ff
inactive_colors={color5}ff, {color1}ff, {color1}ff, {color7}ff, {color1}ff, {color1}ff, {color3}ff, {color5}ff, {color1}ff, {color1}ff, {color1}ff, {color1}ff, {color3}ff, {color3}ff, {color3}ff, {color1}ff, {color5}ff, {color1}ff, {color3}ff, {color1}ff, {color3}ff, {color2}ff

