#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

time=$(date +%Y-%m-%d-%H-%M-%S)
screen=$(xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current')
dir="$(xdg-user-dir VIDEOS)/Screenrecorder"
file="Capture_${time}.mp4"
iDir="$HOME/.config/dunst/icons/dunst"

# common ffmpeg output options for maximum compatibility
OUT_OPTS=(
	-c:v libx264
	-preset ultrafast
	-crf 23
	-pix_fmt yuv420p
	-r 25
	-vsync cfr
	-movflags +faststart
	-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2"
)

notify_user () {
	notify_cmd="notify-send -u low -i $iDir/video.png"
	if [[ -e "$dir/$file" ]]; then
		${notify_cmd} "Saved in $dir"
	else
		${notify_cmd} "Video Deleted."
	fi
}

countdown () {
	for sec in $(seq "$1" -1 1); do
		notify-send -t 1000 -i "$iDir/timer.png" "Starting in : $sec"
		sleep 1
	done
}

rec_screen() {
	countdown '5'
	if [[ "$1" == "noaudio" ]]; then
		ffmpeg -video_size "${screen}" -framerate 25 -f x11grab -i :0.0+0,0 \
			"${OUT_OPTS[@]}" "${dir}"/"${file}"
	else
		ffmpeg -video_size "${screen}" -framerate 25 -f x11grab -i :0.0+0,0 \
			-f pulse -ac 2 -i default \
			"${OUT_OPTS[@]}" -c:a aac -b:a 192k "${dir}"/"${file}"
	fi
	notify_user
}

rec_area() {
	get_win_data=$(slop -f "%x %y %w %h %g %i") || exit 1
	read -r X Y W H G ID < <(echo "$get_win_data")

	countdown '5'
	if [[ "$1" == "noaudio" ]]; then
		ffmpeg -video_size "${W}"x"${H}" -framerate 25 -f x11grab -i :0.0+"${X}","${Y}" \
			"${OUT_OPTS[@]}" "${dir}"/"${file}"
	else
		ffmpeg -video_size "${W}"x"${H}" -framerate 25 -f x11grab -i :0.0+"${X}","${Y}" \
			-f pulse -ac 2 -i default \
			"${OUT_OPTS[@]}" -c:a aac -b:a 192k "${dir}"/"${file}"
	fi
	notify_user
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--screen" ]]; then
	rec_screen
elif [[ "$1" == "--area" ]]; then
	rec_area
elif [[ "$1" == "--screen-na" ]]; then
	rec_screen noaudio
elif [[ "$1" == "--area-na" ]]; then
	rec_area noaudio
else
	echo -e "Available Options : --screen   --screen-na   --area   --area-na"
fi

exit 0
