#!/usr/bin/env bash

BRIGHTNESS=$(brightness --get)

if [[ $BRIGHTNESS -ge 80 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 60 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 40 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 20 ]]; then
  ICON=" "
fi

colorbox -t "$ICON$BRIGHTNESS" -f color1 -b color15
