#!/usr/bin/env bash
red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"

BRIGHTNESS=$(brightness --get)

if [[ $BRIGHTNESS -ge 80 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 60 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 40 ]]; then
  ICON=" "
elif [[ $BRIGHTNESS -ge 20 ]]; then
  ICON=" "
fi

echo "^c$black^^b$yellow^$ICON$BRIGHTNESS^d^"
