#!/usr/bin/env bash
#
#
#
# Colors

case $BLOCK_BUTTON in
1)
  setsid -f "$TERMINAL" -c 'floating' -T "Dates" -e calcurse
  pkill -RTMIN+7 "${STATUSBAR:-dwmblocks}"
  ;;
2) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e' | tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
colorbox -i "📆" -t "$(date '+%I:%M:%S')" -f color9
