#!/usr/bin/env bash

case $BLOCK_BUTTON in
1)
  setsid -f "$TERMINAL" -c 'floating' -T "Progress" -e btop
  ;;
2) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

colorbox -i " " -t "$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf 100 - $1"%"}')"\
  -f color14
