#!/usr/bin/env bash

red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"

case $BLOCK_BUTTON in
1)
  setsid -f "$TERMINAL" -c 'floating' -T "Progress" -e btop
  ;;
2) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo -e "^b$orange^^c$black^ $(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf 100 - $1"%"}')^d^"
