#!/usr/bin/env bash

case $BLOCK_BUTTON in
1)
  setsid -f "$TERMINAL" -c 'floating' -T "Progress" -e btop
  ;;
2) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
colorbox -i "⚡" -t " $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)" -f color5
