#!/bin/bash
Players=$(playerctl -l 2>/dev/null)

playing_player=""

# Check the status of each player
for player in $Players; do
  status=$(playerctl --player=$player status 2>/dev/null)
  if [[ "$status" == "Playing" ]]; then
    playing_player=$player
    break
  fi
done
Info=$(playerctl --player=$playing_player metadata | grep "title" | awk -F'xesam:title' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); split($2, a, " - "); print a[1] "-" a[2]}')

case $BLOCK_BUTTON in
# right click, pause/unpause
1)
  if [[ -n "$playing_player" ]]; then
    notify-send "Player $playing_player" "$Info"
  else
    setsid -f "$TERMINAL" --class 'FloatMusic' -T "Music" -e ncmpcpp
  fi
  ;;

3)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" play-pause
  else
    mpc toggle
  fi
  ;; # right click, pause/unpause
  # right click, pause/unpause
4)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" previous
  else
    mpc prev
  fi
  ;; # scroll up, previous
5)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" next
  else
    mpc next
  fi
  ;; # scroll down, next
esac

online=$(timeout 2 mpc 2>/dev/null)

if [ ! "$online" = "" ]; then
  title=$(mpc -f "%title%" | head -n 1)
  if [[ -n "$playing_player" ]]; then
    if [[ $playing_player = "Goodvibes" ]]; then
      colorbox -i "🌐" -t "{${Info:0:20}}" -f color11
    else
      colorbox -i "🌐" -t "{${Info:0:20}}" -f color11
    fi
  fi

  if [ "$(echo "$online" | wc -l)" -le 1 ]; then
    colorbox -i "🎵" -t "{###}" -f color7
  elif [ ! "$title" = "" ]; then
    colorbox -i "🎵 " -t "{${title:0:20}}" -f color12
  else
    colorbox -i "🎵" -t "{$(mpc -f "%artist%" | head -n 1)}" -f color12
  fi
else
  colorbox -i "✖️" -t "{Offline}" -f color3
fi
