#!/bin/bash
Players=$(playerctl -l 2>/dev/null)

playing_player=""

# Check the status of each player
for player in $Players; do
  status=$(playerctl --player=$player status 2>/dev/null)
  if [[ "$status" == "Playing" ]]; then
    playing_player=$player
    break
  fi
done
Info=$(playerctl --player=$playing_player metadata | grep "title" | awk -F'xesam:title' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); split($2, a, " - "); print a[1] "-" a[2]}')

case $BLOCK_BUTTON in
# right click, pause/unpause
1)
  if [[ -n "$playing_player" ]]; then
    notify-send "Player $playing_player" "$Info"
  else
    setsid -f "$TERMINAL" --class 'FloatMusic' -T "Music" -e ncmpcpp
  fi
  ;;

3)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" play-pause
  else
    mpc toggle
  fi
  ;; # right click, pause/unpause
  # right click, pause/unpause
4)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" previous
  else
    mpc prev
  fi
  ;; # scroll up, previous
5)
  if [[ -n "$playing_player" ]]; then
    playerctl --player="$playing_player" next
  else
    mpc next
  fi
  ;; # scroll down, next
esac

red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"
online=$(timeout 2 mpc 2>/dev/null)

if [ ! "$online" = "" ]; then
  title=$(mpc -f "%title%" | head -n 1)
  if [[ -n "$playing_player" ]]; then
    if [[ $playing_player = "Goodvibes" ]]; then
      echo -e "^b$purple^^c$black^ ${Info:0:20}^d^"
    else
      echo -e "^b$teal^^c$black^ ${Info:0:20}^d^"
    fi
  fi

  if [ "$(echo "$online" | wc -l)" -le 1 ]; then
    echo -e "^b$blue^^c$black^󰝚 On^d^"
  elif [ ! "$title" = "" ]; then
    echo -e "^b$cyan^^c$black^󰝚 ${title:0:14}^d^"
  else
    echo -e "^b$cyan^^c$black^󰝚 $(mpc -f "%artist%" | head -n 1)^d^"
  fi
else
  echo -e "^c$black^b$red^ﳌ Off^d^"
fi
