#!/usr/bin/env bash
#

case $BLOCK_BUTTON in
1)
  setsid -f "$TERMINAL" --class "FloatTerm" -T "Packages" -e yay
  ;;
3)
  notify-send "Updates" "$(yay -Qu | tr -d ' ')"
  ;;
esac

red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"

echo -e "^c$black^^b$cyan^ $(pacman -Q | wc -l)"
