#!/usr/bin/env bash

red="#FF3131"
purple="#9457EB"
green="#39FF14"
blue="#4D4DFF"
bblue="#89CFF0"
orange="#F6890A"
yellow="#CCFF00"
cyan="#00FEFC"
teal="#43BBB6"
black="#000000"

checkIfRunning() {
  if [ $(systemctl --user is-active redshift) == "active" ]; then
    return 0
  else
    return 1
  fi
}

changeModeToggle() {

  if checkIfRunning; then
    systemctl --user stop redshift
  else
    systemctl --user start redshift
  fi
}

if checkIfRunning; then
  CURRENT_TEMP=$(redshift -P 2>/dev/null | grep "Color temperature" | sed 's/.*: //')
else
  CURRENT_TEMP="Off"
fi

# Handle click and scroll events
case "$BLOCK_BUTTON" in
1)
  changeModeToggle
  ;;
esac

echo -e "^c$black^^b$bblue$^ $CURRENT_TEMP^d^"
