#!/usr/bin/env bash


vol=$(pamixer --get-volume)

[ "$vol" != "${vol%\[MUTED\]}" ] && echo 🔇 && exit

vol="${vol#Volume: }"

split() {
  # For ommiting the . without calling and external program.
  IFS=$2
  set -- $1
  printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
$((vol >= 40))) icon="🔊" ;;
$((vol >= 20))) icon="🔉" ;;
$((vol >= 1))) icon="🔈" ;;
*) echo "🔇 " && exit ;;
esac

colorbox -i "$icon" -t "$vol%" -f color10
# echo "$ICON$VOL%"

case $BLOCK_BUTTON in
1)
  pavucontrol
  ;;
2)
  pamixer -t
  ;;
3)
  setsid -f "$TERMINAL" -e "$EDITOR" "$0"
  ;;
4)
  pamixer -i 2
  ;;
5)
  pamixer -d 2
  ;;
esac
