#!/usr/bin/env bash

ALL=$(fd --type=file --extension=kitty-session --hidden  --absolute-path . 2>/dev/null)

SEL=$(echo -e "$ALL" | dmenu -W 600 -l 10 -p " ")

if [ -n "$SEL" ]; then
  kitty --session "$SEL"
fi
